# Basic settings

font:
  normal:
    family: Hack Nerd Font
    style: Medium
    size: 12

# Colors

colors:
  # Normal colors
  black: "#282c34"
  red: "#ff6c6b"
  green: "#98c379"
  yellow: "#d79921"
  blue: "#6c757d"
  magenta: "#c678dd"
  cyan: "#4db5bd"
  white: "#f1f2f3"
  light-black: "#3c3f48"
  light-red: "#d79921"
  light-green: "#b5e585"
  light-yellow: "#ffffb3"
  light-blue: "#85999c"
  light-magenta: "#c08e93"
  light-cyan: "#548dd4"

  # Bright colors
  bright-black: "#3c3f48"
  bright-red: "#ff5370"
  bright-green: "#c0ca33"
  bright-yellow: "#f7e91e"
  bright-blue: "#83a598"
  bright-magenta: "#d65d80"
  bright-cyan: "#26a69a"
  bright-white: "#ffffff"

# Theming

theme: Dracula
