# version 13 or above support toml config

# for windows move this folder to %APPDATA% path
# for linux move this folder to $HOME/.config/ path

import = ["./alacritty-themes/carbonfox.toml"]

[shell]
program = "powershell"

[font]
size = 12

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9
decorations = "full"

[window.padding]
x = 12
y = 12

[window.dimensions]
columns = 90
lines = 25

[cursor]
style.shape = "Block"
style.blinking = "Always"
