# version 13 or above support toml config

# for windows move this folder to %APPDATA% path
# for linux move this folder to $HOME/.config/ path

import = ["./alacritty-themes/carbonfox.toml"]

[shell]
program = "powershell"

[terminal]
osc52 = "CopyPaste"

[font]
size = 12

[window]
dimensions = { columns = 90, lines = 30 }
padding = { x = 12, y = 12 }
startup_mode = "Windowed"
decorations = "full"
dynamic_padding = true

[cursor]
style = { blinking = "Always", shape = "Block" }
thickness = 0.8
